### ISSUE TITLE
psql problem

### ISSUE THREAD

**Issue by Hasi123** [dbrgn/hnf-peaks#2]
I installed the prerequisites on WSL Ubuntu and tried to run 1-load-osm-data.sh, but get the following error:

> david@DESKTOP-EJC33T5:~/hnf-peaks$ ./1-load-osm-data.sh austria
> psql: could not connect to server: No such file or directory
>         Is the server running locally and accepting
>         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by dbrgn** [comment]
Is a PostgreSQL server (with PostGIS) installed and started?

**Comment by Hasi123** [comment]
I only followed your Readme. How do I do that?

**Comment by dbrgn** [comment]
Check out https://www.postgresql.org/download/. You need both PostgreSQL and the PostGIS extension: https://postgis.net/install/

From your description it seems you're using Windows + WSL? I think it should be possible to install Postgres + PostGIS within the WSL environment, but I don't have much experience with that.

Maybe this link helps: https://medium.com/@harshityadav95/postgresql-in-windows-subsystem-for-linux-wsl-6dc751ac1ff3

**Comment by Hasi123** [comment]
I did install the extensions, but didn't know that I had to start some
server. I'll check it out when I get home. Thanks!

**Comment by Hasi123** [comment]
Still get some errors...

> postgres@DESKTOP-EJC33T5:~/hnf-peaks$ ./1-load-osm-data.sh Austria
> Downloading Austria-latest.osm.pbf...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   284  100   284    0     0    755      0 --:--:-- --:--:-- --:--:--   755
> Removing and recreating outdir "peaks_Austria"...
> Osmosis not found. Downloading...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   640  100   640    0     0   1259      0 --:--:-- --:--:-- --:--:--  1257
> 100 14.4M  100 14.4M    0     0  4532k      0  0:00:03  0:00:03 --:--:-- 6971k
> Extracting data...
> Sep 14, 2020 9:51:38 PM org.openstreetmap.osmosis.core.Osmosis run
> INFO: Osmosis Version 0.48.2
> Sep 14, 2020 9:51:39 PM org.openstreetmap.osmosis.core.Osmosis run
> INFO: Preparing pipeline.
> Sep 14, 2020 9:51:39 PM org.openstreetmap.osmosis.core.Osmosis run
> INFO: Launching pipeline execution.
> Sep 14, 2020 9:51:39 PM org.openstreetmap.osmosis.core.Osmosis run
> INFO: Pipeline executing, waiting for completion.
> Sep 14, 2020 9:51:39 PM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
> SEVERE: Thread for task 1-read-pbf failed
> org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to process PBF stream
>         at crosby.binary.osmosis.OsmosisReader.run(OsmosisReader.java:48)
>         at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: org.openstreetmap.osmosis.osmbinary.file.FileFormatException: Unexpectedly long header 65536 bytes. Possibly corrupt file.
>         at org.openstreetmap.osmosis.osmbinary.file.FileBlockHead.readHead(FileBlockHead.java:50)
>         at org.openstreetmap.osmosis.osmbinary.file.FileBlock.process(FileBlock.java:130)
>         at org.openstreetmap.osmosis.osmbinary.file.BlockInputStream.process(BlockInputStream.java:34)
>         at crosby.binary.osmosis.OsmosisReader.run(OsmosisReader.java:45)
>         ... 1 more
> 
> Sep 14, 2020 9:51:39 PM org.openstreetmap.osmosis.core.Osmosis main
> SEVERE: Execution aborted.
> org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
>         at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
>         at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
>         at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
>         at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

**Comment by dbrgn** [comment]
Can you try a lowercase country name?

    ./1-load-osm-data.sh austria

**Comment by dbrgn** [comment]
Should be fixed by 3742f8eccbce2692692aebd74c53fd0990c1ae72 and c7c92c8f6aa405a35cc18452eeadd56b249d16fb.
